[workspace]
members = ["cesriding", "cesrinf", "cesrinf-wasm", "cesrinfo-web"]
resolver = "2"

[workspace.dependencies]
colored = "2.1.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
