[package]
name = "common-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { workspace = true }

askama = { version = "0.12.1", features = ["markdown"] }
askama_axum = "0.4.0"
