[package]
name = "cesrinf"
version = "0.1.0"
edition = "2021"


[dependencies]
colored = { workspace = true }

base64 = "0.21.7"
clap = { version = "4.5.0", features = ["derive"] }
rstest = "0.18.2"

serde = { workspace = true }
serde_json = { workspace = true }
