spin_manifest_version = 2

[application]
name = "cesrinf-web-spin"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "cesrinf-web-spin"

[[trigger.http]]
route = "/static/..."
component = "fileserver"

[component.cesrinf-web-spin]
source = "target/wasm32-wasi/release/cesrinf_web_spin.wasm"
[component.cesrinf-web-spin.build]
command = "cargo build --target wasm32-wasi --release"

[component.fileserver]
files = [{ source = "static/", destination = "/" }]
[component.fileserver.source]
url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm"
digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f"
