spin_manifest_version = 2

[application]
name = "cesrinf-web-spin"
version = "0.1.0"

# index

[[trigger.http]]
route = "/..."
component = "index"

[component.index]
source = "index/target/wasm32-wasi/release/index.wasm"
[component.index.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "index"
watch = ["src/**/*.rs", "Cargo.toml"]

# cesr

[[trigger.http]]
route = "/cesr"
component = "cesr"

[component.cesr]
source = "cesr/target/wasm32-wasi/release/cesr.wasm"
allowed_outbound_hosts = []
[component.cesr.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "cesr"
watch = ["src/**/*.rs", "Cargo.toml"]

# spin-fileserver

[[trigger.http]]
route = "/static/..."
component = "fileserver"

[component.fileserver]
files = [{ source = "static/", destination = "/" }]
[component.fileserver.source]
url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm"
digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f"
