[package]
name = "cesr"
authors = ["Stănilă Ioan <ioanstanilais@gmail.com>"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cesrinf = { path = "../../../cesrinf" }

anyhow = "1"
spin-sdk = "2.2.0"
serde = "1.0.197"
serde_json = "1.0.115"
